title: Omhari Gurung
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: Experienced Data Entry Specialist and Small Business Owner with a strong background in financial operations,
data accuracy, and process improvement. Making a career change and diving headfirst into the world of data
analytics. Proficient in Excel, SQL, Tableau, and Data visualization. Growing fluency in Python and R.
  <a href="https://www.linkedin.com/in/omhari-gurung-950877243/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
